theme: jekyll-theme-minimal
title: "Gustavo Enrique Ramos Alcaraz"
description: "PhD in Electronics and Telecommunications at CICESE"
logo: /assets/img/profile.jpeg
css: /assets/css/style.css

# Navigation menu
links:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
    
