#theme: jekyll-theme-minimal #First Setting.
remote_theme: pages-themes/minimal@v0.2.0 # Theme Info: https://github.com/pages-themes/minimal
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Gustavo Ramos"
description: "PhD in Electronics and Telecommunications at CICESE"
logo: /assets/img/profileMod.jpeg
#show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: [G-9ZRXBX9NY9]
